markdown: kramdown
highlighter: pygments

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/style-guide"

version: 0.1.0

port: 8888
host: localhost

github:
  repo: https://github.com/daptiv/style-guide
